class CustomException(object):
    def custom_exception(self, exception: str) -> str:
        pass